name: pipeline
on: [push] 
jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses : azure/login@v1
        with :
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: checkout source code
        uses: actions/checkout@v2
      - name: Deploy Delsos auth app 
        uses: azure/CLI@v1
        with: 
          inlineScript: |
            az deployment group create \
            --name DelsosAuthDeployement \
            --resource-group Delsos-group \
            --template-file package-lock.json \
            --parameters storageAccountType=Standard_GRS


       
      