name: pipeline
on: [push] 
jobs:
  build:
    runs-on: ubuntu-latest
    needs: 
      - Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dockerihem/delsos:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses : azure/login@v1
        with :
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: checkout source code
        uses: actions/checkout@v2
      - name : Setup
        uses : actions/setup-node@v3
       
      - name: Deploy Delsos auth app 
        uses: azure/webapps-deploy@v2
        with: 
          app-name: delsos
          package : ./app
    